### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML , CSS, and JavaScript files
- [x] Create div for container, background image, and car image
- [x] Add favicon to head element
- [x] Add background color
- [x] Add car image to file
- [x] Style car to appropriate size
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
