### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create and link data.js for data model.
- [x] Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x] Add direction class to car image based on direction and data model
- [x] Listen for 'keydown' events on the document.
- [x] Create function to change car direction.
- [x] Based on key pressed, change data model direction property. (w = north, a = west, s = south, d =east)
- [x] Based on key pressed, change img class to direction in data model.
- [x] Change car img direction when key pressed.
- [x] Add rotate transition based on change in direction (may need to add delay?)
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
