### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] Add condition if 'space' is pressed to event listener
- [x] Create function that will increment offset x variable by 5 ???
- [x] Concatenate offset x variable with 'px' to turn to string ???? 
- [x] Assign concatenated value to element.style.left ???
- [x] Add setInterval method to run function when space bar is clicked ???
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] Move your car every 16 milliseconds for a smooth movement.
- [x] Update data model xCoord variable with offset x variable ????
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
