### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a property to your data model to indicate whether or not the car engine is on.
- [x] Pressing space will change engine value in data model
- [x] Create condition to setInterval if engine off
- [x] Create condition to clearInterval if engine on 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
