### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Change moveCar function conditions to data model direction.
- [x] Add conditions for west, south, and north
- [x] Set west to offsetX -= 5
- [x] Set north to offsetY -=5
- [x] Set south to offsetY += 5
